### ISSUE TITLE
Missing header when building with mingw on win32

### ISSUE THREAD

**Issue by rhaamo** [chris5287/QWidgetMap#12]
Got:

```
'runtime_error' is not a member of 'std'
```

Fixed with (http://stackoverflow.com/questions/4861777/missing-stdruntime-error-in-qtmingw):
Add `#include <stdexcept>` in qwidgetmap_global.h

**Comment by rhaamo** [comment]
Update: same problem on Debian with GCC

**Comment by chris5287** [comment]
The missing `#include <stdexcept>` needs to be included in QWidgetMap/src/QWidgetMap/projection/Projection.cpp
