### ISSUE TITLE
Totally unusable on Windows

### ISSUE THREAD

**Issue by rhaamo** [chris5287/QWidgetMap#13]
It just doesn't works on Windows, works fine on Mac, Debian but Windows it just _explodes_...

Built examples and my own app using QWidgetMap : 
- Builds fine.
- Starting from explorer freeze explorer.
- Starting from QtDesigner freeze QtDesigner.

Using QtDesigner 3.5.1and Qt 5.5.1 MinGW 32bit (4.9.2).

**Comment by chris5287** [comment]
QWidgetMap has only been tested with MSVC 12 (VS 2013) on Windows.

I am unsure how QWidgetMap could even freeze Explorer?

**Comment by rhaamo** [comment]
Good question, even the example freeze QtDesigner and nothing get running.
(I was able to build and run properly my own app without QWidgetMap integration even on Win32)

Edit: I'm trying to install VS 2015 to try building with an official MSVC if it runs properly.

**Comment by rhaamo** [comment]
The example was built and run successfully with MSVC2013 32bit.
It should be notified in the README that only MSVC2013 is compatible and no Mingw even if it builds... (at least for Win32 platform)
